[workspace]
members = [
    "sbe",
    "api",
    "me",
    "md/level2",
    "md/ticker",
    "ws",
    "tr",
]

resolver = "3"

[workspace.dependencies]
sbe = { path = "sbe" }

[workspace.package]
edition = "2024"
