[package]
name = "md"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
redis = { version = "0.29.1", features = [] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"