[package]
name = "aeron-sub"
version = "0.1.0"
edition = "2024"

[dependencies]
aeron-rs = "0.1.8"
chrono = "0.4.41"
ctrlc = "3.4.7"
lazy_static = "1.5.0"
nix = "0.30.1"
pretty_env_logger = "0.5.0"
priority-queue = "2.3.1"
sbe = { path = "../sbe" }
slab = "0.4.9"
uuid = "1.17.0"
