[package]
name = "matching-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
sbe = { workspace = true }
aeron-rs = "0.1.8"
priority-queue = "2.3.1"
slab = "0.4.9"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"